import type { Metadata } from "next";
import { Box, Container, MantineProvider } from "@mantine/core";
import "@mantine/core/styles.css";
import "./globals.css";
import customTheme from "@/theme";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <MantineProvider theme={customTheme} defaultColorScheme="dark">
          <Container
            bg={"dark.8"}
            size="full"
            px={0}
            py={0}
            style={{ minHeight: "100vh" }}
          >
            {children}
          </Container>
        </MantineProvider>
      </body>
    </html>
  );
}
